[build]
  command = "npm run build"        # Comando para buildar seu projeto
  publish = "dist"                 # Pasta onde está o site estático gerado (build output)
  functions = "netlify/functions" # Pasta onde ficam suas funções serverless Netlify
